name: bmi_calculator
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # font-awesome icons
  font_awesome_flutter: ^9.1.0

  # in app web View
  webview_flutter: ^4.0.2

  # cache local data
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # splash screen
  flutter_native_splash: ^2.2.16

  # change application id
  change_app_package_name: ^1.1.0

flutter_native_splash:
  color: "#090C22"
  image: "assets/bmi.png"

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
          weight: 400

  assets:
    - assets/bmi.png
