// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABj_9vCOGz1rNN0WbGCoU0yrJBn4yKtwU',
    appId: '1:1097657830790:web:5365de97225af6d980f007',
    messagingSenderId: '1097657830790',
    projectId: 'solobit-bmi-calculator',
    authDomain: 'solobit-bmi-calculator.firebaseapp.com',
    storageBucket: 'solobit-bmi-calculator.appspot.com',
    measurementId: 'G-SSV8LVLJFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtdfdaj6kQx104ghrRaMLXnFCopSt6jis',
    appId: '1:1097657830790:android:66b7b75ccb924d2c80f007',
    messagingSenderId: '1097657830790',
    projectId: 'solobit-bmi-calculator',
    storageBucket: 'solobit-bmi-calculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmenVEMSE0Z-31NJeXD95yOQFwoj8e3lY',
    appId: '1:1097657830790:ios:feeda4885b78e59580f007',
    messagingSenderId: '1097657830790',
    projectId: 'solobit-bmi-calculator',
    storageBucket: 'solobit-bmi-calculator.appspot.com',
    iosBundleId: 'com.solobit.bmiCalculator',
  );
}
